-- Active: 1736276969157@@127.0.0.1@5432@learn
CREATE DATABASE learn;

/* 
    double quote "" is using for table, name, column name....
    single quote is using for values

    example : INSERT INTO "employees" ("name", "username") VALUE ('Nichola', 'Nik');
*/  

-- USE learn; -- if use SQL Client
-- \c learn; -- if use CLI

/* 
    to create AUTO_INCREMENT in postgres we can use SERIAL/BIGSERIAL, where automatically creates;
    1. AUTO_INCREMENT
    2. INTEGER (4 BYTES)
    3. NOT NULL
*/

/* 
    little bit about constraintm is rule that have data can be consistent; LIKE 
    1. NOT NULL
    2. Unique
    3. PRIMARY KEY
    4. FOREIGN KEY - Reference to other column value at another table
    5. CHECK 
    6. DEFAULT
*/

-- CREATE TABLE users
CREATE TABLE users (
    id SERIAL PRIMARY KEY, -- CREATE SERIAL LIKE THIS ITS NOT RECOMMEND NOW
    name VARCHAR(64) NOT NULL,
    username VARCHAR(32) NOT NULL UNIQUE
)

-- DESCRIBE TABLE users
SELECT 
    COLUMN_NAME,
    DATA_TYPE, 
    CHARACTER_MAXIMUM_LENGTH,
    IS_NULLABLE
FROM 
    information_schema.columns
WHERE
    TABLE_NAME = 'users';

/* 
    Or If Using CLI Just Try This
    - \d users

    if want to see all table
    - \dt
*/

/*
    a sequence is a database object that generates a unique series of numbers, typically used for auto-incrementing primary key columns.
*/
-- CREATE SEQUENCE 
CREATE SEQUENCE employees_id_seq;
-- CREATE TABLE employees
CREATE TABLE employees (
    id INTEGER PRIMARY KEY DEFAULT nextval('employees_id_seq') NOT NULL,
    name VARCHAR(64) NOT NULL,
    username VARCHAR(64) NOT NULL
);

-- CREATE TABLE customers 
CREATE TABLE customers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    username VARCHAR(64) NOT NULL
);

-- EDIT TABLE customers 
ALTER TABLE customers 
    ADD COLUMN phone INT;

-- EDIT TABLE users
ALTER TABLE users
    ALTER COLUMN name TYPE VARCHAR(255);

-- DROP TABLE customers
DROP TABLE customers;

-- INSERT DATA TO employees
INSERT INTO "employees" ("name", "username") VALUES ('Nichola', 'NIK');

-- INSERT MULTIPLE employees
INSERT INTO "employees" ("name", "username") VALUES 
    ('JOKO MORRO', 'JOKO'),
    ('BUDI HANDOKO', 'BUDI'),
    ('ELSA JALPASA', 'ECA');

-- SIMPLE SELECT employees;
SELECT id, name, username FROM employees;

-- UPDATE employees
UPDATE employees SET name = 'NICHOLA' WHERE id = 1;

-- MULTIPLE UPDATE employees
UPDATE employees 
    SET name = 'ELSA JAPASA',
        username = 'ECA AURA'
        WHERE id = 4; 

-- DELETE employees;
DELETE FROM employees WHERE id = 4;


-- SHOW TABLES
SELECT TABLE_NAME FROM information_schema.tables WHERE table_schema = 'public';

/*
    JSON
*/

ALTER TABLE users 
    ADD COLUMN "details" JSONB;

INSERT INTO users ("name", "username", "details") VALUES 
    ('Nichola', 'Nik', 
    '{
        "Country" : "Indonesia",
        "Regency" : "East Java",
        "Hobbies" : ["Coding", "Sleep", "Eat"]
    }'
    )

-- SELECT * users
SELECT * FROM users;    

-- GET JSON OBJECT FIELD
SELECT details -> 'Hobbies' FROM "users";
SELECT details -> 'Country' FROM "users";
SELECT details -> 'Regency' FROM "users";